In [66]:
import numpy as np

In [67]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

mean_a = a.mean(axis = 0)

In [68]:
print("Среднее значение по каждому признаку: ", mean_a)

Среднее значение по каждому признаку:  [2.  8.4]


In [69]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [70]:
c = a_centered[:, 0]
b = a_centered[:, 1]
print(c, b)

[-1.  0.  1.  1. -1.] [-2.4 -0.4  2.6  1.6 -1.4]


In [71]:
a_centered_sp = c.dot(b)
print(a_centered_sp)

8.0


In [72]:
rows, columns = a.shape

print("Rows = ",rows)
print("Columns = ", columns)

Rows =  5
Columns =  2


In [73]:
print(a_centered_sp/(rows-1))

2.0


In [81]:
a_t = np.transpose(a)
print(a_t)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [103]:
a_cov = np.cov(a_t)
print(a_cov[0, 1])

2.0
