In [69]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from math import *

In [70]:
%matplotlib inline

1.

In [71]:
a = np.linspace(12, 24, 12, endpoint=False).astype(int)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2.

In [72]:
b1 = np.reshape(a, (12, 1))
b2 = np.reshape(a, (2, 6))
b3 = np.reshape(a, (6, 2))
b4 = np.reshape(a, (3, 4))
b5 = np.reshape(a, (4, 3))

In [73]:
print(f'{b1},\n {b2},\n {b3},\n {b4},\n {b5}')

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]],
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]],
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]],
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]],
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


3.

In [74]:
b1 = np.reshape(a, (12, -1))
b2 = np.reshape(a, (-1, 6))
b3 = np.reshape(a, (6, -1))
b4 = np.reshape(a, (-1, 4))
b5 = np.reshape(a, (4, -1))
print(f'{b1},\n {b2},\n {b3},\n {b4},\n {b5}')

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]],
 [[12 13 14 15 16 17]
 [18 19 20 21 22 23]],
 [[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]],
 [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]],
 [[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


4.

Нет.
Одномерный массив — массив, с одним параметром, характеризующим количество элементов одномерного массива. 
Фактически одномерный массив — это массив, у которого может быть только одна строка, и n-е количество столбцов. 
Столбцы в одномерном массиве — это элементы массива.

5.

In [75]:
b = np.random.randn(3, 4)
b

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [76]:
b.size

12

In [77]:
h = b.flatten()
h

array([ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337,
       -0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004,
       -0.46341769, -0.46572975])

In [78]:
h.size

12

In [79]:
h.size == b.size

True

6. 

In [80]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7.

In [81]:
b1 = np.reshape(np.arange(20, 0, -2), (1, 10))
b1

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

в первом случае одномерный массив, во втором двумерный массив с одной строкой. 

8.

In [82]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
print('A', a, sep='\n')
print('B', b, sep='\n ')
v = np.concatenate((a, b), axis = 0)
print('V', v, sep='\n')
v.size

A
[[0. 0.]
 [0. 0.]
 [0. 0.]]
B
 [[1. 1.]
 [1. 1.]]
V
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


10

9.

In [83]:
a = np.linspace(0, 12, 12, endpoint=False).astype(int)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [84]:
A = np.reshape(a, (4, 3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [86]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [87]:
B.size

16

Матрицы A и At можно умножить друг на друга, если число столбцов первой матрицы равняется числу строк второй матрицы. 
В таком случае результатом умножения будет матрица В с количеством строк как у первой матрицы, а столбцов у второй. 

In [91]:
B_det = np.linalg.det(B)
B_det

0.0

Вычислить обратную матрицу нельзя, т.к. определитель равен 0

10.

In [92]:
import random
random.seed(42)
print(random.random())


0.6394267984578837


11.

In [96]:
c = np.linspace(0, 16, 16, endpoint=False).astype(int)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

12.

In [100]:
C = np.reshape(c, (4, 4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
D = B * (C * 10)
D

array([[    0,   140,   460,   960],
       [  560,  2500,  5160,  8540],
       [ 1840,  7740, 14900, 23320],
       [ 3840, 15860, 29680, 45300]])

In [103]:
D_det = np.linalg.det(D)
print("Определитель: ", D_det)

Определитель:  -7.956259651109595e-05


In [105]:
D_inv = np.linalg.inv(D)
print("Обратная матрица: ", D_inv)  

Обратная матрица:  [[-4.88671835e+11  1.46601550e+12 -1.46601550e+12  4.88671835e+11]
 [ 1.46601550e+12 -4.39804651e+12  4.39804651e+12 -1.46601550e+12]
 [-1.46601550e+12  4.39804651e+12 -4.39804651e+12  1.46601550e+12]
 [ 4.88671835e+11 -1.46601550e+12  1.46601550e+12 -4.88671835e+11]]


In [106]:
D_rank = np.linalg.matrix_rank(D)
print("Ранг матрицы: ", D_rank) 

Ранг матрицы:  3


13.

In [107]:
positive = D_inv > 0
negative = D_inv < 0
D_inv[positive] = 1
D_inv[negative] = 0
D_inv



array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [108]:
E = np.where(D_inv, B, C)
E

array([[  0,  14,   2,  32],
       [ 14,   5,  86,   7],
       [  8,  86,  10, 212],
       [ 32,  13, 212,  15]])